
services:
  debug:
    image: ci-all:latest
    container_name: debug-container
    networks:
      - test-network
    volumes:
      - .:/app
    working_dir: /app
    command: bash

  backend:
    image: ci-all:latest
    container_name: test-backend
    networks:
      - test-network
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/backend
    command: bash -c "cd /app/backend && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    image: ci-all:latest
    container_name: test-frontend
    networks:
      - test-network
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app/frontend
    command: bash -c "cd /app/frontend && npm run dev  --host 0.0.0.0"
    
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://172.21.0.3:5173/ || exit 1"]
      interval: 2s
      retries: 30

  run_backend_tests:
    image: ci-all:latest
    networks:
      - test-network
    volumes:
      - .:/app
    command: bash -c "cd /app/backend && pytest"
    
     
        
  run_cypress:
    image: ci-all:latest
    networks:
      - test-network
    volumes:
      - .:/app
    working_dir: /app/frontend
    environment:
      CYPRESS_BASE_URL: http://172.21.0.3:5173
    command: bash -lc "cd /app/frontend && npm run build && npx cypress run --config baseUrl=http://172.21.0.3:5173"
    
     

networks:
  test-network:
    driver: bridge
      
